# Common playbook.
#
# Contains the common parts for development and production setup.
---

- hosts: all

  become: true
  become_method: sudo
  become_user: root

  pre_tasks:
    - name: Update apt cache (if old)
      apt: update_cache=yes cache_valid_time=84600
      changed_when: false

  vars:
      nodejs_install_npm_user: "root"
      nodejs_user: "vagrant"
      adminapp_packagejson_folder: "/vagrant/src/adminapp/frontend"
      webapp_packagejson_folder: "/vagrant/src/webapp/frontend"

  roles:
  - git
  - role: pip_requirements
    pip_req_file: "requirements/common.txt"
  - i18n
  - geerlingguy.nodejs
  - role: build_node_frontend
    packagejson_folder: "{{ adminapp_packagejson_folder }}"
  - role: build_node_frontend
    packagejson_folder: "{{ webapp_packagejson_folder }}"
  - build_dev_backend

...
