# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-17 19:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=20)),
                ('notes', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'key entry',
                'verbose_name_plural': 'key entries',
            },
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20)),
                ('key_entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='passwords', to='api.KeyEntry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passwords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'password',
                'verbose_name_plural': 'passwords',
            },
        ),
    ]
