# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-20 16:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=2000)),
                ('username', models.CharField(blank=True, max_length=2000)),
                ('url', models.CharField(blank=True, max_length=2000)),
                ('notes', models.CharField(blank=True, max_length=2000)),
            ],
            options={
                'verbose_name': 'key entry',
                'verbose_name_plural': 'key entries',
            },
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=2000)),
                ('key_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passwords', to='api.KeyEntry')),
            ],
            options={
                'verbose_name': 'password',
                'verbose_name_plural': 'passwords',
            },
        ),
        migrations.CreateModel(
            name='PublicKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=2000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='public_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'public key',
                'verbose_name_plural': 'public keys',
            },
        ),
        migrations.AddField(
            model_name='password',
            name='public_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passwords', to='api.PublicKey'),
        ),
        migrations.AlterUniqueTogether(
            name='password',
            unique_together=set([('key_entry', 'public_key')]),
        ),
    ]
