# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-17 19:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='public_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'public key',
                'verbose_name_plural': 'public keys',
            },
        ),
    ]
