# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-17 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_publickey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyentry',
            name='notes',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='keyentry',
            name='title',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='keyentry',
            name='url',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='keyentry',
            name='username',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='publickey',
            name='key',
            field=models.CharField(max_length=2000),
        ),
    ]
