# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-20 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('api', '0002_auto_20180720_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyentry',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='key_entries', to='auth.Group'),
            preserve_default=False,
        ),
    ]
