# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-17 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180717_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyentry',
            name='notes',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='keyentry',
            name='title',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='keyentry',
            name='url',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='keyentry',
            name='username',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
