# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-17 20:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_auto_20180717_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='key_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passwords', to='api.KeyEntry'),
        ),
        migrations.AlterUniqueTogether(
            name='password',
            unique_together=set([('key_entry', 'user')]),
        ),
    ]
