Commands
========

.. autosummary::
    :nosignatures:

    core.management.commands.celery.Command
    core.management.commands.celery_beat.Command
    core.management.commands.makemessages.Command
    core.management.commands.postfix.Command
    core.management.commands.postgres.Command
    core.management.commands.rabbitmq.Command
    core.management.commands.solr.Command
 
core.management.commands.celery
-------------------------------
.. autoclass:: core.management.commands.celery.Command
    :members:

core.management.commands.celery_beat
------------------------------------
.. autoclass:: core.management.commands.celery_beat.Command
    :members:

core.management.commands.makemessages
-------------------------------------
.. autoclass:: core.management.commands.makemessages.Command
    :members:

core.management.commands.postfix
--------------------------------
.. autoclass:: core.management.commands.postfix.Command
    :members:
    
core.management.commands.postgres
---------------------------------
.. autoclass:: core.management.commands.postgres.Command
    :members:

core.management.commands.rabbitmq
---------------------------------
.. autoclass:: core.management.commands.rabbitmq.Command
    :members:

core.management.commands.solr
-----------------------------
.. autoclass:: core.management.commands.solr.Command
    :members:
